# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, lib, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.supportedFilesystems = [ "overlay" "btrfs" "zfs" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
  ];
  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
  '';
  boot.kernelPackages = pkgs.linuxPackages;
  boot.kernelParams = [
    "amd_pstate=active"
  ];
  networking.hostId = "4ce220a9";

  boot.zfs.requestEncryptionCredentials = [];

  boot.initrd.extraUtilCommands = let
    cfgZfs = config.boot.zfs;
  in ''
    copy_bin_and_libs ${pkgs.gnupg}/bin/
    copy_bin_and_libs ${pkgs.gnupg}/bin/addgnupghome
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpg
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpgscm
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpgv
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpg-mail-tube
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/dirmngr_ldap
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/gpg-check-pattern
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/gpg-preset-passphrase
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/gpg-wks-client
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/scdaemon
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/gpg-auth
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/gpg-pair-tool
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/gpg-protect-tool
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/keyboxd
    copy_bin_and_libs ${pkgs.gnupg}/bin/libexec/tpm2daemon
    copy_bin_and_libs ${pkgs.gnupg}/bin/applygnupgdefaults
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpgsm
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpg-agent
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpg-wks-client
    copy_bin_and_libs ${pkgs.gnupg}/bin/watchgnupg
    copy_bin_and_libs ${pkgs.gnupg}/bin/dirmngr
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpgconf
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpgsplit
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpg-card
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpg-wks-server
    copy_bin_and_libs ${pkgs.gnupg}/bin/dirmngr-client
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpgparsemail
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpgtar
    copy_bin_and_libs ${pkgs.gnupg}/bin/gpg-connect-agent
    copy_bin_and_libs ${pkgs.gnupg}/bin/kbxutil
    copy_bin_and_libs ${pkgs.pcscliteWithPolkit}/bin/pcscd
    copy_bin_and_libs ${cfgZfs.package}/sbin/zfs
    copy_bin_and_libs ${cfgZfs.package}/sbin/zdb
    copy_bin_and_libs ${cfgZfs.package}/sbin/zpool
    copy_bin_and_libs ${cfgZfs.package}/lib/udev/vdev_id
    copy_bin_and_libs ${cfgZfs.package}/lib/udev/zvol_id
  '';
  boot.initrd.postResumeCommands = lib.mkAfter ''
    mkdir -p /mnt/zpool/public
    mount -t zfs -o zfsutil zpool/public /mnt/zpool/public
    pcscd --auto-exit
    gpg-agent --daemon
    gpg --import /mnt/zpool/public/canokey.asc
    gpg --pinentry-mode loopback --decrypt /mnt/zpool/public/zpool.key.gpg | zfs load-key -- zpool/keys
    mkdir -p "/Y:/"
    mount -t zfs -o zfsutil zpool/keys "/Y:/"
    zfs load-key -a
    umount "/Y:/"
    umount /mnt/zpool/public
  '';
  boot.initrd.systemd.enable = false;

  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;
  hardware.graphics.extraPackages = [
    pkgs.amdvlk # for Vulkan
    # pkgs.rocmPackages.clr.icd # for OpenCL support
  ];
  hardware.graphics.extraPackages32 = [
    pkgs.driversi686Linux.amdvlk # for Vulkan
  ];
  hardware.amdgpu.initrd.enable = true;

  hardware.bluetooth.enable = true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    neededForBoot = true;
    options = [ "defaults" "size=64G" "mode=755" ];
  };

  fileSystems."/nix" = {
    device = "zpool/nixos";
    fsType = "zfs";
    neededForBoot = true;
    options = [ "zfsutil" ];
    depends = [ "/mnt/keys" ];
  };

  fileSystems."/nix/persist" = {
    device = "zpool/nixos/persist";
    fsType = "zfs";
    neededForBoot = true;
    options = [ "zfsutil" ];
    depends = [ "/nix" ];
  };

  fileSystems."/mnt/shared" = {
    device = "zpool/shared";
    fsType = "zfs";
    options = [ "zfsutil" ];
    depends = [ "/" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/889D-C417";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/2dec9ec9-8ea9-4cb7-8250-dd1fd9757614";
    }
  ];

}
